export const CITIES = [
    'paris', 'marseille', 'lyon', 'toulouse', 'nice', 'nantes', 'strasbourg', 'montpellier',
    'bordeaux', 'lille', 'rennes', 'reims', 'le-havre', 'saint-etienne', 'toulon', 'grenoble',
    'dijon', 'angers', 'villeurbanne', 'le-mans', 'saint-denis', 'aix-en-provence', 'brest',
    'nimes', 'limoges', 'clermont-ferrand', 'tours', 'amiens', 'metz', 'perpignan', 'besancon',
    'boulogne-billancourt', 'orleans', 'mulhouse', 'rouen', 'caen', 'argenteuil', 'saint-paul',
    'montreuil', 'nancy', 'roubaix', 'tourcoing', 'nanterre', 'avignon', 'vitry-sur-seine',
    'creteil', 'dunkerque', 'poitiers', 'asnieres-sur-seine', 'versailles', 'colombes',
    'saint-pierre', 'aubervilliers', 'aulnay-sous-bois', 'courbevoie', 'cherbourg-en-cotentin',
    'fort-de-france', 'rueil-malmaison', 'champigny-sur-marne', 'pau', 'beziers', 'la-rochelle',
    'saint-maur-des-fosses', 'calais', 'cannes', 'antibes', 'drancy', 'mamoudzou', 'ajaccio',
    'merignac', 'saint-nazaire', 'colmar', 'issy-les-moulineaux', 'noisy-le-grand', 'cergy',
    'vaulx-en-velin', 'levallois-perret', 'valence', 'bourges', 'pessac', 'ivry-sur-seine',
    'quimper', 'la-seyne-sur-mer', 'antony', 'villeneuve-d\'ascq', 'clichy', 'troyes',
    'montauban', 'neuilly-sur-seine', 'sarcelles', 'niort', 'chambery', 'pantin', 'le-blanc-mesnil',
    'la-roche-sur-yon', 'bondy', 'saint-quentin', 'evry-courcouronnes', 'maisons-alfort',
    'cholet', 'vannes', 'chelles', 'epinay-sur-seine', 'fontenay-sous-bois', 'frejus',
    'narbonne', 'lorient', 'sartrouville', 'bobigny', 'grasse', 'sevran', 'laval', 'belfort',
    'albi', 'evreux', 'corbeil-essonnes', 'vincennes', 'montrouge', 'martigues', 'cagnes-sur-mer',
    'bayonne', 'saint-ouen-sur-seine', 'brive-la-gaillarde', 'suresnes', 'carcassonne',
    'saint-malo', 'blois', 'hyeres', 'meudon', 'saint-brieuc', 'chalons-en-champagne',
    'alfortville', 'clamart', 'puteaux', 'valenciennes', 'choisy-le-roi', 'arles', 'boulogne-sur-mer',
    'saint-herblain', 'salon-de-provence', 'rosny-sous-bois', 'saint-priest', 'massy', 'livry-gargan',
    'charleville-mezieres', 'beauvais', 'tarbes', 'wattrelos', 'bezons', 'angouleme', 'douai',
    'saint-germain-en-laye', 'melun', 'gagny', 'draguignan', 'colomiers', 'garges-les-gonesse',
    'la-courneuve', 'savigny-sur-orge', 'bron', 'saint-martin', 'compiegne', 'noisy-le-sec',
    'meaux', 'le-lamentin', 'saint-martin-d\'heres', 'marcq-en-baroeul', 'annemasse', 'saint-raphael',
    'bagnolet', 'pontault-combault', 'le-perreux-sur-marne', 'castres', 'anglet', 'thionville',
    'cambrai', 'montlucon', 'villejuif', 'vitrolles', 'saint-sebastien-sur-loire', 'sainte-genevieve-des-bois',
    'roanne', 'conflans-sainte-honorine', 'neuilly-sur-marne', 'auxerre', 'saint-chamond',
    'chatillon', 'vigneux-sur-seine', 'nevers', 'plaisir', 'tremblay-en-france', 'montigny-le-bretonneux',
    'franconville', 'annecy', 'sainte-marie', 'rambouillet', 'villeneuve-saint-georges', 'ermont',
    'vitry-le-francois', 'stains', 'sens', 'le-chesnay-rocquencourt', 'dumbea', 'libourne',
    'six-fours-les-plages', 'romans-sur-isere', 'chatenay-malabry', 'herblay-sur-seine', 'dole',
    'mantes-la-jolie', 'chalon-sur-saone', 'montgeron', 'chartres', 'poissy', 'sete', 'chatellerault',
    'viry-chatillon', 'nogent-sur-marne', 'epinal', 'villepinte', 'dieppe', 'athis-mons',
    'le-gosier', 'perigueux', 'saint-cloud', 'macon', 'thonon-les-bains', 'goussainville',
    'villefranche-sur-saone', 'vienne', 'chatou', 'malakoff', 'trappes', 'aix-les-bains',
    'matoury', 'savigny-le-temple', 'creteil', 'cachan', 'schiltigheim', 'royan', 'pontoise',
    'charenton-le-pont', 'rillieux-la-pape', 'agen', 'bois-colombes', 'saint-medard-en-jalles',
    'le-cannet', 'bastia', 'saintes', 'agde', 'laon', 'miramas', 'orvault', 'les-mureaux',
    'bergerac', 'muret', 'oyonnax', 'saint-dizier', 'draveil', 'sucy-en-brie', 'taverny',
    'brignoles', 'villiers-sur-marne', 'rochefort', 'saint-laurent-du-maroni', 'carpentras',
    'bourg-en-bresse', 'menton', 'noumea', 'abbeville', 'cavaillon', 'gif-sur-yvette',
    'sainte-anne', 'beziers', 'saint-die-des-vosges', 'champs-sur-marne', 'grigny', 'palaiseau',
    'saint-michel-sur-orge', 'saint-andre', 'les-ulis', 'echirolles', 'villiers-le-bel',
    'kourou', 'sotteville-les-rouen', 'saumur', 'dax', 'longjumeau', 'saint-joseph', 'haguenau',
    'allauch', 'saint-leu', 'brunoy', 'saint-gratien', 'yerres', 'le-bouscat', 'lanester',
    'vandoeuvre-les-nancy', 'pierrefitte-sur-seine', 'villeneuve-la-garenne', 'coudekerque-branche',
    'sarreguemines', 'maubeuge', 'chatillon', 'le-kremlin-bicetre', 'fontaine', 'begles',
    'decines-charpieu', 'blagnac', 'lunel', 'bayeux', 'frontignan', 'montbeliard', 'biarritz'
] as const;

export type City = typeof CITIES[number];

export function capitalizeCity(city: City): string {
    return city.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('-');
}